# Generated by Django 3.2.23 on 2023-11-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imcookingdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserEmail2',
            field=models.CharField(default='xx', max_length=100),
            preserve_default=False,
        ),
    ]
