# Generated by Django 3.2.23 on 2024-01-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imcookingdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientTypes',
            fields=[
                ('TypeId', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='TypeId',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientType', to='imcookingdb.ingredienttypes'),
        ),
    ]
