# Generated by Django 3.2.23 on 2023-11-23 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imcookingdb', '0002_user_useremail2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe2',
            fields=[
                ('RecipeId', models.AutoField(primary_key=True, serialize=False)),
                ('RecipeTitle', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
