# Generated by Django 3.2.23 on 2023-11-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imcookingdb', '0003_recipe2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe2',
        ),
    ]
