# Generated by Django 3.2.23 on 2023-12-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imcookingdb', '0004_delete_recipe2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='RecipeIngredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='RecipeSteppes',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='RecipePhoto',
            field=models.ImageField(upload_to='recipe_photos/'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='imcookingdb.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='imcookingdb.recipe')),
            ],
        ),
    ]
