# Generated by Django 3.2.23 on 2023-12-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imcookingdb', '0005_auto_20231212_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientTypes',
            fields=[
                ('TypeId', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=50)),
            ],
        ),
    ]
