# Generated by Django 3.2.23 on 2023-12-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imcookingdb', '0006_ingredienttypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='Amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='TypeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='CookTime',
            field=models.IntegerField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='PrepTime',
            field=models.IntegerField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Rating',
            field=models.FloatField(null=True),
        ),
    ]
