# Generated by Django 3.2.23 on 2023-12-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imcookingdb', '0007_auto_20231217_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='StepOrder',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='CookTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='PrepTime',
            field=models.IntegerField(null=True),
        ),
    ]
