# Generated by Django 3.2.23 on 2024-01-01 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imcookingdb', '0008_auto_20231217_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttypes',
            name='Ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='IngredientType', to='imcookingdb.ingredient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
